# Generated by Django 3.1.4 on 2021-04-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slb1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='available',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
