# Generated by Django 3.1.4 on 2021-04-23 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slb1', '0002_equipments_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
