# Generated by Django 3.1.4 on 2021-04-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slb1', '0005_equipments_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
