# Generated by Django 3.1.4 on 2021-04-24 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slb1', '0007_auto_20210424_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='date_returned',
        ),
    ]
