# Generated by Django 3.1.4 on 2021-04-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slb1', '0010_reserve_collect'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
