# Generated by Django 3.1.4 on 2021-04-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slb1', '0011_students_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
